- name: deploy app
  hosts: all
  become: true
  vars:
    deployment_path: "/home/ubuntu/app"
    compose_path: "./docker-compose.yml"
  roles: 
    - geerlingguy.docker
  tasks:
    - name: update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install pip3
      package:
        name: python3-pip
        state: present
    - name: install docker-compose pip
      pip:
        name:
          - docker<7.0
          - docker-compose
    - name: create file
      file:
        path: "{{ deployment_path }}"
        state: directory
        mode: '0755'
    - name: copy
      copy:
        src: "{{ compose_path }}"
        dest: "{{ deployment_path }}"
      
    - name: run docker-compose up
      become: true
      community.docker.docker_compose_v2:
        project_src: "{{ deployment_path }}"
        #build: yes
        #debug: yes
      environment:
        FRONTEND_IMAGE: "{{ lookup('env','FRONTEND_IMAGE') }}"
        BACKEND_IMAGE: "{{ lookup('env','BACKEND_IMAGE') }}"



        


      